stack_name: "cfn-lambda-benchmark"
bucket_name: "bkt-lambda-benchmark"
log_retention_in_days: 7
iterations_lambdas: 5
iterations_code: 50
schedule_state: ENABLED # 'ENABLED' or 'DISABLED'
schedule_expression: "cron(0 14 * * ? *)"

step_functions: EXPRESS # 'EXPRESS' or 'STANDARD'
step_functions_debug: false

memory_sizes:
  - 128
  - 256
  - 384
  - 512
  - 640
  - 768
  - 896
  - 1024
  - 1152
  - 1280
  - 1408
  - 1536
  - 1664
  - 1792
  - 1920
  - 2048
  - 2176
  - 2304
  - 2432
  - 2560
  - 2688
  - 2816
  - 2944
  - 3072
  - 3200
  - 3328
  - 3456
  - 3584
  - 3712
  - 3840
  - 3968
  - 4096
