[package]
name = "cfn_gen"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1.0"
walkdir = "2.4"
