name: Build and upload to S3

on:
  workflow_dispatch:

jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt-get update
          sudo apt-get install yq -y
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true
      - name: "Find, Parse, Build and Deploy"
        run: |
          paths=$(find runtimes -type f -name build.sh -exec dirname {} \;)
          
          for path in $paths
          do
            echo "Processing $path..."
          
            architectures=$(yq e "$path/manifest.yml" -j | jq -r '.architectures[]')
          
            chmod +x "$path/build.sh"
          
            for arch in $architectures
            do
              echo "Building $path for architecture: $arch..."
              (cd "$path" && ./build.sh "$arch")
            done
          
            echo "Build and actions for $path complete."
          done
