name: manual

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'runtime'
        type: choice
        options:
          - dotnet8al2023
        required: true
      architecture:
        description: 'architecture'
        type: choice
        options:
          - x86_64
          - arm64
        required: true

jobs:
  build:

    name: "${{ inputs.runtime }} ${{ inputs.architecture }} build"
    runs-on: ${{ inputs.architecture == 'arm64' && 'macos-14' || 'ubuntu-latest' }}

    permissions:
      contents: read

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install docker
          colima start

      - name: Run script
        run: |
          cd ./runtimes/${{inputs.runtime}} && ./build.sh ${{ inputs.architecture }}

      - name: Save code.zip
        uses: actions/upload-artifact@v4
        with:
          name: dotnet8al2023_${{ inputs.architecture }}.zip
          path: ./runtimes/${{ inputs.runtime }}/dotnet8al2023_${{ inputs.architecture }}.zip
