name: Deploy stack to AWS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true
      - name: "Install Rust toolchain"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: "Generate template"
        run: |
          cargo run --bin cfn-gen
      - name: "SAM Deploy"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SAM_CLI_TELEMETRY: 0
        run: |
          stack_name=$(sed -n 's/stack_name: "\(.*\)"/\1/p' parameters.yml)
          echo "Stack Name: $stack_name"
          bucket_name=$(sed -n 's/bucket_name: "\(.*\)"/\1/p' parameters.yml)
          echo "Bucket Name: $bucket_name"
          sam package \
            --template-file template.yml \
            --output-template-file packaged-template.yml \
            --s3-bucket $bucket_name
          sam deploy \
            --template-file packaged-template.yml \
            --stack-name $stack_name \
            --capabilities CAPABILITY_NAMED_IAM \
            --region $AWS_REGION \
            --s3-bucket $bucket_name
