name: Deploy to AWS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true
      - name: "Install Rust toolchain"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: "Install SAM CLI"
        run: |
          wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
          unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
          ./sam-installation/install
          sam --version
      - name: "Generate template"
        run: |
          cargo run --bin cfn-gen
      - name: "SAM Deploy"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          stack_name=$(sed -n 's/stack_name: "\(.*\)"/\1/p' parameters.yml)
          bucket_name=$(sed -n 's/bucket_name: "\(.*\)"/\1/p' parameters.yml)
          sam package \
            --template-file template.yml \
            --output-template-file packaged-template.yml \
            --s3-bucket $bucket_name
          sam deploy \
            --template-file packaged-template.yml \
            --stack-name $stack_name \
            --capabilities CAPABILITY_IAM \
            --region $AWS_REGION
